
version: 2

models:
  - name: dim_aircraft
    description: "Aircraft information"
    columns:
    - name: id
      description: "The primary key for this table"
      tests:
       - unique
       - not_null

  - name: dim_airport
    description: "Airport information"
    columns:
    - name: id
      description: "The primary key for this table"
      tests:
       - unique
       - not_null


sources:
  - name: dim_stg
    database: flights_demo
    schema: stg
    tables:
      - name: aircrafts_data
      - name: seats
      - name: airports_data
      
